# Numpy 

In [ ]:
print("Hello world")

#Importing numpy and checking version

In [4]:
import numpy as np
print(np.__version__)


1.20.3


In [5]:
import numpy

arr = numpy.array([1, 2, 3, 4, 5])

print(arr)

[1 2 3 4 5]


In [7]:
import numpy 
arr=numpy.array(['A','B',5,7])
print(arr)

['A' 'B' '5' '7']


In [8]:
import numpy 
arr= numpy.array([1,2,3,4,5,6])
print(arr)
print(type(arr))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [9]:
import numpy 

arr=np.array((1,2,3,4,5))
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


1-d arrays in numpy

In [15]:
import numpy 
arr=numpy.array([1,2,3])
print(arr.shape)

(3,)


2-D array 

In [17]:
import numpy 

arr=numpy.array([[1,2,3],[4,5,6]])
print(arr.shape)
# Shape return (rows , column)

(2, 3)


3-D array in numpy

In [20]:
import numpy 
arr= np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(arr)
print(arr.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
(2, 2, 3)


In [25]:
import numpy as np 
a=np.array(42)
b=np.array([1,2,3,4,5])
c=np.array([[1,2,3],[4,5,6]])
d=np.array([[[1,2,3],[4,5,6]],[[1,2,3],[4,5,6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [27]:
import numpy as np 
arr=np.array([1,2,3,4],ndmin=5)

print(arr)
print('number of dimensions : ',arr.ndim)

[[[[[1 2 3 4]]]]]
number of dimensions :  5


Acceccing array elements

In [28]:
import numpy as np
arr= np.array([1,2,3,4,5])
print(arr[0])

1


In [31]:
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr[-1]+arr[0])

6


In [32]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("2nd element of 1st row : ",arr[0,1])

2nd element of 1st row :  2


In [38]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("2nd element of 1st row : ",arr[1,-1])

2nd element of 1st row :  10


In [33]:
import numpy as np
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print("5th element of 2nd row : ",arr[1][4])

5th element of 2nd row :  10


In [36]:
import numpy as np 
arr=np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])

print(arr[0,1,2])


6


Slicing in array numpy

In [39]:
import numpy as np 
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[1:5])

[2 3 4 5]


In [40]:
import numpy as np
arr= np.array([1,2,3,4,5,6,7,8,9])
print(arr[4:])

[5 6 7 8 9]


In [41]:
import numpy as np 
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[:5])

[1 2 3 4 5]


In [43]:
import numpy as np 
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[-5:-1])

[5 6 7 8]


In [44]:
import numpy as np 
arr=np.array([1,2,3,4,5,6,7,8,9])

print(arr[1:7:2])

[2 4 6]


In [46]:
import numpy as np 
arr=np.array([1,2,3,4,5,6,7,8,9])
print(arr[::2])

[1 3 5 7 9]


In [48]:
import numpy as np 
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[1,1:3])

[7 8]


In [49]:
import numpy as np 
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,2])

[3 8]


In [50]:
import numpy as np 
arr=np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(arr[0:2,1:3])

[[2 3]
 [7 8]]


Below is a list of all data types in NumPy and the characters used to represent them.

i - integer
b - boolean
u - unsigned integer
f - float
c - complex float
m - timedelta
M - datetime
O - object
S - string
U - unicode string
V - fixed chunk of memory for other type ( void )

strings - used to represent text data, the text is given under quote marks. e.g. "ABCD"
integer - used to represent integer numbers. e.g. -1, -2, -3
float - used to represent real numbers. e.g. 1.2, 42.42
boolean - used to represent True or False.
complex - used to represent complex numbers. e.g. 1.0 + 2.0j, 1.5 + 2.5j

In [51]:
import numpy as np

arr=np.array([1,2,3,4,5])
print(arr.dtype)

int32


In [54]:
import numpy as np
arr=np.array(['Apple','Orange','Banana','Cherry'])
print(arr.dtype)

<U6


In [56]:
import numpy as np 
arr=np.array([1,2,3,4],dtype='S')
print(arr)
print(arr.dtype)

[b'1' b'2' b'3' b'4']
|S1


# Type casting in Numpy using .astype(type)

In [58]:
import numpy as np

arr = np.array([1.1, 2.1, 3.1])

newarr = arr.astype('i')

print(newarr)
print(newarr.dtype)
print(arr.dtype)

[1 2 3]
int32
float64


In [ ]:
import numpy as np

arr = np.array([1, 0, 3])

newarr = arr.astype(bool)

print(newarr)
print(newarr.dtype)

Difference between copy and view

In [59]:
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.copy()
arr[0]=42

print(arr)
print(x)

[42  2  3  4  5]
[1 2 3 4 5]


In [60]:
import numpy as np 
arr=np.array([1,2,3,4,5])
x=arr.view()
arr[0]=42
print(arr)
print(x)

[42  2  3  4  5]
[42  2  3  4  5]


The view SHOULD be affected by the changes made to the original array.

In [62]:
import numpy as np
arr=np.array([1,2,3,4,5])
x=arr.copy()
y=arr.view()
print(x.base)
print(y.base)

None
[1 2 3 4 5]


Shape and Reshapes in Array


In [2]:
import numpy as np 
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr.shape)


(2, 4)


In [3]:
import numpy as np 
arr=np.array([1,2,3,4],ndmin=5)
print(arr)
print('Shape of array :',arr.shape)

[[[[[1 2 3 4]]]]]
Shape of array : (1, 1, 1, 1, 4)


In [5]:
import numpy as np 
arr =np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(4,3)
print(newarr)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [6]:
import numpy as np 
arr=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
newarr=arr.reshape(2,3,2)
print(newarr)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]]


In [2]:
import numpy as np

arr=np.array([1,2,3,4,5,6,7,8,1,2,3,4,5,6,7,8,6,5])
newarr=arr.reshape(2,3)
print(newarr) 

# this will give error because in reshape(3,3) total element is 3*3=9 so we have less element in it .

# reshape(n,m) the total element present in the list should be in multiple of n*m 

ValueError: cannot reshape array of size 18 into shape (2,3)

In [3]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

newarr = arr.reshape(2, 2, -1)

print(newarr)

# Pass -1 as the value, and NumPy will calculate this number for you
# We can not pass -1 to more than one dimension.

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


# NumPy Array Iterating

In [5]:
import numpy as np 
arr=np.array([1,2,3,4,5])
for i in arr:
    print(i)

1
2
3
4
5


In [10]:
import numpy as np 
arr= np.array([[1,2,3],[4,5,6]])
# print(arr)
for i in arr:
    for j in i:
        print(j)
    print("\n")

1
2
3


4
5
6




In [16]:
import numpy as np
arr= np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
for i in arr:
    for j in i:
        for k in j:
            print(k, end="*")
        print("#")
    print("x")
        

1*2*3*#
4*5*6*#
x
7*8*9*#
10*11*12*#
x


* Iterating on Each Scalar Element

In [22]:
import numpy as np

arr = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
# print(np.nditer(arr))
for x in np.nditer(arr):
  print(x)

1
2
3
4
5
6
7
8


In [23]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

for x in np.nditer(arr[:, ::2]):
  print(x)

1
3
5
7


* Iterating Array With Different Data Types

In [24]:
import numpy as np

arr = np.array([1, 2, 3])

for x in np.nditer(arr, flags=['buffered'], op_dtypes=['S']):
  print(x)


b'1'
b'2'
b'3'


* Enumerated Iteration Using ndenumerate()

In [28]:
import numpy as np
arr=np.array([1,2,3])
for idx , x in np.ndenumerate(arr):
    print(idx,x)


(0,) 1
(1,) 2
(2,) 3


In [34]:
import numpy as np 
arr= np.array([[1,2,3,4],[5,6,7,8]])
for idx , x in np.ndenumerate(arr):
    print(idx,x)

(0, 0) 1
(0, 1) 2
(0, 2) 3
(0, 3) 4
(1, 0) 5
(1, 1) 6
(1, 2) 7
(1, 3) 8


# Joining arrays

* one to one stack 

In [38]:
import numpy as np 
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
newarr=np.stack((arr1,arr2),axis=1)
print(newarr)

[[1 4]
 [2 5]
 [3 6]]


* Horizontal Stacking Along Rows

In [42]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.hstack((arr1, arr2))

print(arr)


[1 2 3 4 5 6]


In [43]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.concatenate((arr1, arr2))

print(arr)

[1 2 3 4 5 6]


* Vertical Stack Stacking Along Columns

In [40]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.vstack((arr1, arr2))

print(arr)

[[1 2 3]
 [4 5 6]]


* Stacking Along Height (depth)

In [41]:
import numpy as np

arr1 = np.array([1, 2, 3])

arr2 = np.array([4, 5, 6])

arr = np.dstack((arr1, arr2))

print(arr)

[[[1 4]
  [2 5]
  [3 6]]]


# Splitting NumPy Arrays

In [48]:
import numpy as np

arr = np.array([1, 2, 3,4,5,6,7,8,9])
newarr = np.array_split(arr, 3)

for i in newarr:
    for j in i:
        print(j)
    print("*")
print(newarr)

1
2
3
*
4
5
6
*
7
8
9
*
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [49]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 4)


print(newarr)

# If the array has less elements than required, it will adjust from the end accordingly.

[array([1, 2]), array([3, 4]), array([5]), array([6])]


In [50]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

newarr = np.array_split(arr, 3)

print(newarr[0])
print(newarr[1])
print(newarr[2])

[1 2]
[3 4]
[5 6]


2d array slpit 

In [51]:
import numpy as np

arr = np.array([[1, 2], [3, 4], [5, 6], [7, 8], [9, 10], [11, 12]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]


* Split the 2-D array into three 2-D arrays.

In [52]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3)

print(newarr)

[array([[1, 2, 3],
       [4, 5, 6]]), array([[ 7,  8,  9],
       [10, 11, 12]]), array([[13, 14, 15],
       [16, 17, 18]])]


* Split the 2-D array into three 2-D arrays along rows.

In [ ]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

* Use the hsplit() method to split the 2-D array into three 2-D arrays along rows.

In [53]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


 * Similar alternates to vstack() and dstack() are available as vsplit() and dsplit().

# Search in array 

In [54]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 4, 4])

x = np.where(arr == 4)

print(x)
# indeces

(array([3, 5, 6], dtype=int64),)


* Find the indexes where the values are even

In [59]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 0)

print(x)
# indeces which condition is satified

(array([1, 3, 5, 7], dtype=int64),)


* Find the indexes where the values are odd

In [ ]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8])

x = np.where(arr%2 == 1)

print(x)

* Find the indexes where the value 7 should be inserted:

In [61]:
import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7)

print(x)

1


* Find the indexes where the value 7 should be inserted, starting from the right:

In [62]:
import numpy as np

arr = np.array([6, 7, 8, 9])

x = np.searchsorted(arr, 7, side='right')

print(x)

2


* Find the indexes where the values 2, 4, and 6 should be inserted:

In [63]:
import numpy as np

arr = np.array([1, 3, 5, 7])

x = np.searchsorted(arr, [2, 4, 6])

print(x)

[1 2 3]


# Sorting

In [64]:
import numpy as np

arr = np.array([3, 2, 0, 1])

print(np.sort(arr))

[0 1 2 3]


* Sort Alphabetically

In [ ]:
import numpy as np

arr = np.array(['banana', 'cherry', 'apple'])

print(np.sort(arr))

* sort boolean value

In [65]:
import numpy as np

arr = np.array([True, False, True])

print(np.sort(arr))

[False  True  True]


* sort 2d array

In [66]:
import numpy as np

arr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(arr))

[[2 3 4]
 [0 1 5]]


# Filterning 

* Create an array from the elements on index 0 and 2:

In [67]:
import numpy as np

arr = np.array([41, 42, 43, 44])

x = [True, False, True, False]

newarr = arr[x]

print(newarr)

# Because the new filter contains only the values where the filter array had the value True, in this case, index 0 and 2.

[41 43]


* Create a filter array that will return only values higher than 42:

In [69]:
import numpy as np

arr = np.array([41, 42, 43, 44])

# Create an empty list
filter_arr = []

# go through each element in arr
for element in arr:
  # if the element is higher than 42, set the value to True, otherwise False:
  if element > 42:
    filter_arr.append(True)
  else:
    filter_arr.append(False)

newarr = arr[filter_arr]

print(filter_arr)
print(newarr)



[False, False, True, True]
[43 44]


## Random

* Generate a random integer from 0 to 100:

In [72]:
from numpy import random

x = random.randint(100)

print(x)

59


* Generate a random float from 0 to 1:

In [76]:
from numpy import random

x = random.rand()

print(x)

0.5907633127056784


* Generate a 1-D array containing 5 random integers from 0 to 100:

In [77]:
from numpy import random

x=random.randint(100, size=(5))

print(x)

[31 17 90 27 37]


* Generate a 2-D array with 3 rows, each row containing 5 random integers from 0 to 100:

In [78]:
from numpy import random

x = random.randint(100, size=(3, 5))

print(x)

[[52 11 99 47 90]
 [15 89 16 50 31]
 [ 2 81 58 96 83]]


* Generate a 1-D array containing 5 random floats:

In [79]:
from numpy import random

x = random.rand(5)

print(x)

[0.78575395 0.53458168 0.67157941 0.26074165 0.61944706]


* Generate a 2-D array with 3 rows, each row containing 5 random numbers:

In [80]:
from numpy import random

x = random.rand(3, 5)

print(x)

[[0.78692073 0.03651402 0.2602418  0.68992792 0.0506024 ]
 [0.90118274 0.3109091  0.58217301 0.05845134 0.37727509]
 [0.95993318 0.49248139 0.09379651 0.61447522 0.33141546]]


* Return one of the values in an array:

In [83]:
from numpy import random

x = random.choice([3, 5, 7, 9])

print(x)

7


* Generate a 2-D array that consists of the values in the array parameter (3, 5, 7, and 9):

In [84]:
from numpy import random

x = random.choice([3, 5, 7, 9], size=(3, 5))

print(x)

[[3 3 3 7 9]
 [9 9 5 5 9]
 [9 3 7 3 7]]
